# theme.toml template for a Hugo theme
name = "Book"
license = "CC-BY-ND-NC 4.0 & MIT"
licenselink = "https://github.com/golang-design/under-the-hood/blob/master/LICENSE"
description = "Go Under The Hood: A source code study"
homepage = "https://github.com/golang-design/under-the-hood"
tags = ["Go 语言原本", "Go", "源码分析", "Source code study", "书", "book", "responsive", "clean"]
features = []
min_version = "0.10"

[author]
  name = "Changkun Ou"
  homepage = "https://changkun.de/"
