baseURL = "http://golang.design/under-the-hood"
languageCode = "zh-cn"
title = "Go 语言原本"
theme = "book"

[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4
[markup.goldmark.renderer]
    unsafe= true